# Generated by Django 3.1.5 on 2021-01-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='type_c',
            field=models.CharField(choices=[('USER', 'User'), ('STAFF', 'Staff')], default='USER', max_length=10),
        ),
    ]
