# Generated by Django 3.1.5 on 2021-01-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_auto_20210125_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aadhar_card',
        ),
    ]
