# Generated by Django 3.1.5 on 2021-01-25 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Luggage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=60)),
                ('aadhar_card', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('luggage_info', models.TextField(max_length=60)),
                ('wearhouse', models.CharField(choices=[('BALEWADI', 'Balewadi'), ('SHIVAJINAGAR', 'Shivajinagar')], default='BALEWADI', max_length=15)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
